service: client-api

provider:
  name: aws
  runtime: nodejs22.x
  timeout: 300 # Aumente o timeout para 30 segundos (ou mais, se necessário)
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
          Resource: !GetAtt ClientsTable.Arn
        - Effect: Allow
          Action:
            - execute-api:Invoke # Permite que o API Gateway invoque a Lambda
          Resource: arn:aws:execute-api:us-east-1:*:*
  environment:
    CLIENTS_TABLE: !Ref ClientsTable

package:
  individually: true # Define se cada função será empacotada individualmente (true) ou tudo em um único pacote (false)
  exclude:
    - node_modules/aws-sdk/** # Exclui o AWS SDK, pois ele já está disponível no ambiente Lambda
    - .serverless/**          # Exclui a pasta .serverless (gerada durante o empacotamento)
    - src/functions/__tests__/**
  include:
    - src/**                  # Inclui apenas a pasta src, onde está o código da sua aplicação
resources:
  Resources:
    ClientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ClientsTable
        AttributeDefinitions:
          - AttributeName: clientId
            AttributeType: S
        KeySchema:
          - AttributeName: clientId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  createClient:
    handler: src/functions/createClient.handler
    events:
      - http:
          path: clients
          method: post
          

  getClient:
    handler: src/functions/getClient.handler
    events:
      - http:
          path: clients/{clientId}
          method: get
          

  updateClient:
    handler: src/functions/updateClient.handler
    events:
      - http:
          path: clients/{clientId}
          method: put
          

  deleteClient:
    handler: src/functions/deleteClient.handler
    events:
      - http:
          path: clients/{clientId}
          method: delete
          

  listClients:
    handler: src/functions/listClients.handler
    events:
      - http:
          path: clients
          method: get
          